### ISSUE TITLE
Wiki setup tutorial has confusing pom.xml screenshot

### ISSUE THREAD

**Issue by tondzus** [JavaBWAPI/Java-BWAPI-Tutorial#2]
I followed the [wiki tutorial](https://github.com/JavaBWAPI/Java-BWAPI-Tutorial/wiki/Setup) and in the last step, after starting ChaosLauncher the starcraft window froze and eventually crashed. The ExampleBot reported `BWAPI version mismatch, expected: 10002, got: 10003`.

It took me a few minutes to find out that the `pom.xml` screenshot is outdated and the link above it has the current version of JBWAPI and both maven tags in a copy&paste friendly format.

I would suggest either obfuscating the number in the screenshot so that it can't confuse other people, updating the screenshot or simply dropping it altogether.

**Comment by JasperGeurtz** [comment]
Thank you for the feedback! I've blurred the version in the image, please let me know if this makes it less confusing, and close the issue if it does :)

**Comment by tondzus** [comment]
Looks good! Thanks for fixing :)
