### ISSUE TITLE
Erroneous double parantheis in building

### ISSUE THREAD

**Issue by erikmarcus** [JavaBWAPI/Java-BWAPI-Tutorial#3]
On [The building page](https://github.com/JavaBWAPI/Java-BWAPI-Tutorial/wiki/Train), in the code below, there are two closing parentheses on the line `trainer.train(toTrain));` but shouldn't there be only one?

```[java]
// Train units while we can
for (Unit trainer : self.getUnits()) {
    UnitType unitType = trainer.getType();
    if (unitType.isBuilding() && !unitType.buildsWhat().isEmpty()) {
        UnitType toTrain = unitType.buildsWhat().get(0);
        if (game.canMake(toTrain, trainer)) {
            trainer.train(toTrain));
        }
    }
}
```

**Comment by JasperGeurtz** [comment]
Good catch! Should be fixed now

Please close the issue, if this change resolves it

**Comment by JasperGeurtz** [comment]
Closing as this has been [fixed](https://github.com/JavaBWAPI/Java-BWAPI-Tutorial/wiki/Train/_compare/a11af8099eb71645113b4ac19e9e33c1cfc2b3fb)
