### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by Zarrelle** [JavaBWAPI/Java-BWAPI-Tutorial#4]
From following the setup tutorial once I get to the end of step 4.3 and run both the example bot and starcraft through chaoslauncher the following occurs:

"C:\Program Files\Java\jdk-18.0.2.1\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.2\lib\idea_rt.jar=50149:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath C:\SCAI\Bots\ExampleBot\target\classes;C:\Users\ograd\.m2\repository\com\github\JavaBWAPI\JBWAPI\1.5.1\JBWAPI-1.5.1.jar;C:\Users\ograd\.m2\repository\net\java\dev\jna\jna\5.5.0\jna-5.5.0.jar;C:\Users\ograd\.m2\repository\net\java\dev\jna\jna-platform\5.5.0\jna-platform-5.5.0.jar org.example.ExampleBot --add-exports=java.base/jdk.internal.misc.Unsafe=ALL-UNNAMED
Game table mapping not found.
Game table mapping not found.
0 | 19684 | 0 | 440160359
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Connected
Exception in thread "main" java.lang.IllegalAccessError: class bwapi.WrappedBuffer (in unnamed module @0x68837a77) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x68837a77
	at bwapi.WrappedBuffer.<init>(WrappedBuffer.java:20)
	at bwapi.ClientData.<init>(ClientData.java:6)
	at bwapi.Client.connect(Client.java:203)
	at bwapi.Client.reconnect(Client.java:90)
	at bwapi.BWClient.startGame(BWClient.java:45)
	at bwapi.BWClient.startGame(BWClient.java:35)
	at org.example.ExampleBot.run(ExampleBot.java:23)
	at org.example.ExampleBot.main(ExampleBot.java:27)

Process finished with exit code 1

As soon as Starcraft is launched the bot stops with the above exception.

I've tried using "--add-exports=java.base/sun.nio.ch=ALL-UNNAMED" as well as disabling "Use '--release' option for cross-compilation (Java 9 and later)" and neither have had any noticable difference.

**Comment by JasperGeurtz** [comment]
Could you try using the JVM from https://adoptium.net/temurin/releases/?version=18 and let me know if the issue persists?

I can succesfully launch a game (with JBWAPI's develop branch):
```
"C:\Program Files (x86)\Eclipse Adoptium\jdk-18.0.2.101-hotspot\bin\java.exe" 
Game table mapping not found.
Game table mapping not found.
0 | 5364 | 0 | 24788906
1 | 0 | 0 | 0
2 | 0 | 0 | 0
3 | 0 | 0 | 0
4 | 0 | 0 | 0
5 | 0 | 0 | 0
6 | 0 | 0 | 0
7 | 0 | 0 | 0
Connected
Connection successful
Map name: | iCCup | Fighting Spirit 1.3; Map file name: (4)Fighting Spirit.scx
````

Also maybe you could try if v2.0 (instead of 1.5.1) works: https://github.com/JavaBWAPI/JBWAPI/releases/tag/2.0.0

**Comment by JasperGeurtz** [comment]
Actually it's probably the JBWAPI version, 2.0.0 version specifically mentions Java 9-11 support :D

**Comment by Zarrelle** [comment]
aha! I tried version 2.0.0 and it's connected without issue! Looks like that was the issue

**Comment by JasperGeurtz** [comment]
I made v2+ the default in the `README.md`: https://github.com/JavaBWAPI/JBWAPI/commit/4677f15878a7fda032717ae15a9a7ea996e38311

And updated the tutorial: https://github.com/JavaBWAPI/Java-BWAPI-Tutorial/wiki/Setup

Thanks for the feedback, will close this issue
