### ISSUE TITLE
Tutorial progression stopped

### ISSUE THREAD

**Issue by MasterAqu** [JavaBWAPI/Java-BWAPI-Tutorial#5]
Please, don't leave tutorials!

**Comment by JasperGeurtz** [comment]
Hi MasterAqu :) Thanks for your interest in the JBWAPI tutorial. Unfortunately I currently do not have much spare time to commit to this project.

However I can recommend you two excellent ressources that may help:
 - the sscaitt tutorial: https://sscaitournament.com/index.php?action=tutorial
 - the discord for AI/Bot development: https://discord.gg/DqvHsq9

**Comment by MasterAqu** [comment]
Thanks in advice. Maybe one day..
